---
resources:
  - name: code
    type: git
    source:
      uri: https://github.com/strediecosmin/poc-concourse-testcontainers.git

jobs:
  - name: testcontainers
    plan:
      - get: code
        params: {depth: 1}
        trigger: true
      - task: tests
        privileged: true
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: strediecosmin/poc-dind
              tag: latest
          inputs:
            - name: code
          run:
            path: /shared/entrypoint.sh
            args:
              - bash
              - -ceux
              - |
                apt update
                apt install -y openjdk-8-jdk
                apt install -y maven
                cd code/test-code/faster
                ./mvnw clean test verify
